Repository jenkinsci/publish-over-ssh-plugin, pull requests merged in 2022-02, with the labels that each got.

#44 add dependabot configuration
  .github/dependabot.yml
Labels: maintenance

#52 [SECURITY-2291] Unprotected Storage of Credentials
  src/main/java/jenkins/plugins/publish_over_ssh/BapSshHostConfiguration.java
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshHostConfigurationDescriptor.java
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshPublisherPluginDescriptor.java
  src/main/resources/jenkins/plugins/publish_over_ssh/BapSshHostConfiguration/config.jelly
Labels: bug

#54 [SECURITY-2307] do not validate file path to avoid path transversal
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshCredentialsDescriptor.java
Labels: bug

#59 escape javascript the server name
  src/main/java/jenkins/plugins/publish_over_ssh/BapSshHostConfiguration.java
Labels: bug

#58 [SECURITY-2290] check permission as well
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshCredentialsDescriptor.java
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshHostConfigurationDescriptor.java
  src/main/java/jenkins/plugins/publish_over_ssh/descriptor/BapSshPublisherPluginDescriptor.java
Labels: bug

#61 fix never ending escaping javascript
  src/main/java/jenkins/plugins/publish_over_ssh/BapSshHostConfiguration.java
Labels: bug

#55 Add an editorconfig file
  .editorconfig
Labels: chore

#53 Bump minimum supported Jenkins version
  pom.xml
Labels: dependencies

#63 Update Changelog file
  CHANGELOG.md
Labels: documentation
